
import '../style/globals.scss'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'boxicons/css/boxicons.min.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body data-aos-easing="ease-in-out" data-aos-duration="1000" data-aos-delay="0">{children}</body>
      
    </html>
  )
}
